//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nkdb_v3
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMember
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Tribe { get; set; }
        public Nullable<int> RelationshipType { get; set; }
        public string IdNumber { get; set; }
    }
}
